- name: Check files
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la

      - name: Build APK
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          buildozer android debug
